<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Fax Edit</name>
   <tag></tag>
   <elementGuidId>0b9623f2-8301-4a07-931e-7e8a5b499977</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;fax&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='fax']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e69de24b-7a6d-4eb9-a78c-e6ada1bf1c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>097b931d-fe00-490d-aa51-90fe586de95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-icon</value>
      <webElementGuid>bdd1ca0a-8a33-4448-8471-54c22bc15b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rule-minlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5efa7f38-b17d-40b1-a9f4-3d1e37faf220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rule-maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>4377da5c-84db-472c-bca8-cb88f4f8aafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fax</value>
      <webElementGuid>b112fb10-c852-4920-bd42-147f72beca3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e1e9f6b4-fea1-403a-894f-4ca4bef4da67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;companylist&quot;)/div[@class=&quot;company_editpg&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-md-5&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control form-icon&quot;]</value>
      <webElementGuid>fcfb0c19-b941-4ca2-b133-c8f6cfd848f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='fax']</value>
      <webElementGuid>3b2e2da0-cbc3-4bee-b018-896123239235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='companylist']/div[2]/form/div[9]/div/div/div[2]/div/input</value>
      <webElementGuid>0b7b13e0-212c-48cd-b0c8-6837c3b93b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]/div/input</value>
      <webElementGuid>37623bf1-1551-4237-b2bf-93c138d48c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fax']</value>
      <webElementGuid>35155dd0-32a7-47ac-9544-80a66c36cc3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
