<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GST Detail</name>
   <tag></tag>
   <elementGuidId>44bbe43b-dc92-4a60-b404-b7e6f54ca079</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='companylist']/div/div[4]/table/tbody/tr[10]/td[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>dfe03614-f939-4a2b-be72-b8eca8557ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>33AAWPF2337H1ZP</value>
      <webElementGuid>a283e5ba-efcb-4503-839a-bca91be49ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;companylist&quot;)/div[@class=&quot;companydetail_list&quot;]/div[@class=&quot;table-responsive companydetailblocks&quot;]/table[@class=&quot;table table-borderless&quot;]/tbody[1]/tr[10]/td[2]/p[1]</value>
      <webElementGuid>ebbc15a9-f4f2-4dee-8fcc-8d7a484df9e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='companylist']/div/div[4]/table/tbody/tr[10]/td[2]/p</value>
      <webElementGuid>25fd6f44-6473-48b5-bf6d-8cd6adc82fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GST'])[1]/following::p[1]</value>
      <webElementGuid>3d83fa8c-8a00-43b8-adef-7926084216b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Website'])[1]/following::p[2]</value>
      <webElementGuid>e472e4fa-6bb3-4108-b7ad-3ebe61196c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CompanyLogo'])[1]/preceding::p[1]</value>
      <webElementGuid>368037e8-e103-40d9-bbbc-79d0e033bfff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Name'])[2]/preceding::p[1]</value>
      <webElementGuid>f1de57fe-547a-488a-be3e-f6b56a9bfe72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='33AAWPF2337H1ZP']/parent::*</value>
      <webElementGuid>f088c5ee-893a-4d9d-bfed-d60775b5495d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]/p</value>
      <webElementGuid>ad16801c-f9a5-4909-a9bf-e8fa3d0ca780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '33AAWPF2337H1ZP' or . = '33AAWPF2337H1ZP')]</value>
      <webElementGuid>267e1f69-ab8b-4d9b-b4e6-008ab09a013f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
