<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GST Edit</name>
   <tag></tag>
   <elementGuidId>6bd3b14d-a40f-4252-97f6-d08a7fc928ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;gst&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='gst']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e541742-229b-48a7-922a-12efbe30c86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>07f020bc-e965-41e8-b95c-f23f0245fe4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-icon</value>
      <webElementGuid>28e3ee11-d3cc-4af6-a33b-c14422cbf53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rule-minlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>4b82d0a3-1a25-46ef-86ec-9076f92bee37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rule-maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>bd925354-e302-4f09-b3e4-9efdf858f06d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gst</value>
      <webElementGuid>efd78f74-3a16-4c11-8452-d15c133029cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>33AAWPF2337H1ZP</value>
      <webElementGuid>ec394c6b-d293-48a1-b44e-5980375ad54e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;companylist&quot;)/div[@class=&quot;company_editpg&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-md-5&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control form-icon&quot;]</value>
      <webElementGuid>624bc46f-b119-45b2-a2b4-78af5282cdb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='gst']</value>
      <webElementGuid>199b94dc-088b-4c04-aa4f-2993775f9269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='companylist']/div[2]/form/div[11]/div/div/div[2]/div/input</value>
      <webElementGuid>a13f4145-9683-4fc4-983a-3e27758ff7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/div/input</value>
      <webElementGuid>5f089868-dbb5-421c-8086-26a564cb8541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'gst']</value>
      <webElementGuid>1fb8d303-592f-44ce-95f8-d3d1d958a80f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
