<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website Edit</name>
   <tag></tag>
   <elementGuidId>3d869423-81d1-431c-a452-1834fa8d4cf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;website&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='website']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5992ad3-3059-48a9-a22e-e8fdcb046679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71084e29-0cf6-4816-8289-4fb2bcf0f5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-icon</value>
      <webElementGuid>f473d7be-2c4e-4c34-b49d-dd45c4a301e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rule-minlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>559d099a-9b2f-4e6e-bba9-8c4ca160dc89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rule-maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>6228eb49-de49-489d-ac3f-eea830b7256a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>website</value>
      <webElementGuid>ea733b1f-51b2-4df3-8406-08eb34b6f3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>www.rsoft.in/</value>
      <webElementGuid>8723c3fe-2ce0-447b-aa26-f8cab40e8510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;companylist&quot;)/div[@class=&quot;company_editpg&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-md-5&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control form-icon&quot;]</value>
      <webElementGuid>a559a284-f644-4d1b-8084-b231c8c35cde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='website']</value>
      <webElementGuid>121efc8d-7375-41ef-be3a-3a02e481fb31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='companylist']/div[2]/form/div[10]/div/div/div[2]/div/input</value>
      <webElementGuid>c0af1c05-2a65-452e-942b-d055c0ee8088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/input</value>
      <webElementGuid>4f82b8a0-6553-4da4-a361-f7762238a460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'website']</value>
      <webElementGuid>af51361f-bca6-44e1-b840-f14d3afb541c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
