<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Company Name</name>
   <tag></tag>
   <elementGuidId>afe06bae-ec30-4d98-ad18-97095facfef6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#companyname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='companyname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4490cee0-3476-4ee5-af92-a5ceaad370ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eaf8a25b-bd2b-4d1d-82e7-f1cddc98fbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form_allinputs form-icon round</value>
      <webElementGuid>2f0167c7-379b-4807-ab15-dccf35b94270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>companyname</value>
      <webElementGuid>80b33b47-53f2-42dd-89f5-3c822f778a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company Name</value>
      <webElementGuid>80334dd8-adea-4a5c-9d29-0ca49d756006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>companyname</value>
      <webElementGuid>c80d2a11-b657-41a7-8b29-83bb95d88faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value =this.value.toLocaleUpperCase();</value>
      <webElementGuid>3a1e9661-71f2-44bb-8fa0-b8351fd43d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;companyname&quot;)</value>
      <webElementGuid>787c7cb4-d887-491a-8f2e-093d14c0ded6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='companyname']</value>
      <webElementGuid>fd22da84-230c-4446-b8af-90546cf6cad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginform']/fieldset/input</value>
      <webElementGuid>8ef716ac-0632-43fb-a5df-93f2414a5b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/input</value>
      <webElementGuid>444fd0a2-531f-444b-89b7-fe0c268af0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'companyname' and @placeholder = 'Company Name' and @name = 'companyname']</value>
      <webElementGuid>f73ebf1a-69c8-4afd-9308-a74c7fc1b2d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
